print("Tip Calculator")
myBill = float(input("Enter Total bill: "))
tip = int(input("Enter Tip in Percentage: "))
tipAmount = myBill * (tip / 100)
round(tipAmount, 2)
print("You are tipping\033[34m", tipAmount)
totalBill = float(myBill + tipAmount)
round(totalBill, 2)
print("\033[0mTotal Bill: \033[35m", totalBill, "\033[0m")
group = int(
input("How many people are in your group to split the bill equally: "))
perPerson = float(totalBill / group)
round(perPerson, 2)
print("Each pays\033[31m", perPerson, "\033[0m")
