name=input("What is your name: ")
favFood=input("What is your favourite food: ")
favMusic=input("What is your favourite music: ")
location=input("Where do you live: ")
print()
print("You are "+ name)
print("You are probably hungry for " + favFood)
print("and you are definitely getting your groove on to " + favMusic)
print("You are living in the amazing "+ location)
